@Partner_Integration_BFF_HostAddress = http://localhost:5180

POST {{Partner_Integration_BFF_HostAddress}}/api/v1/partner/transactions
Content-Type: application/json

{
  "partnerId": "P-1001",
  "transactionReference": "TXN-99823",
  "amount": 250.00,
  "currency": "USD",
  "timestamp": "2024-05-10T14:30:00Z"
}

###
